In [3]:
import numpy as np

In [3]:
print(np.__version__)#打印版本 下划线为；两个
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/python\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/python\\Library\\include']
blas_opt_inf

In [4]:
Z = np.zeros(10)#
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
Z = np.zeros((10,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#numpy.zeros(shapes,dtype = float , order = "C")
#参数： shapes： int 或int 的元组，如：10、（10,5）
        #dtype: 数据类型
        #order:{"C","F"} 默认为C 是否在内容中以行（C）或列（F）顺序存储多维数据
#返回ndarray

In [8]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size*Z.itemsize)) 

800 bytes


size()函数用于统计矩阵元素个数，或矩阵某一维的元素个数
numpy.size(a,axis = None)
a为矩阵
axis 为int型的可选参数，不指定返回整个矩阵的元素个数 ；0 返回行数；1 返回列数

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [16]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [17]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 反转向量

In [20]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# 创建3*3并且0-8的矩阵

In [21]:
Z = np.arange(9).reshape((3,3))
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)

In [22]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


# 创建一个 3x3 的单位矩阵

In [25]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 创建一个 3x3x3的随机数组

In [26]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.6639827  0.45997065 0.42210071]
  [0.45053537 0.96597867 0.04829564]
  [0.00112939 0.67585709 0.11984068]]

 [[0.06776938 0.66645859 0.63282996]
  [0.92971726 0.23543588 0.36280928]
  [0.01787005 0.51315655 0.98293214]]

 [[0.39315239 0.03519567 0.65352802]
  [0.41302695 0.71787331 0.32539299]
  [0.7512936  0.36278301 0.3859695 ]]]


# 创建一个 10x10 的随机数组并找到它的最大值和最小值 

In [27]:
Z = np.random.random((10,10))
Zmin,Zmax = Z.min(),Z.max()
print(Zmin,Zmax)

0.014598518329067778 0.993904039905328


# 创建一个长度为30的随机向量并找到它的平均值

In [28]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.47483773475984764


# 创建一个二维数组，其中边界值为1，其余值为0

In [29]:
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 对于一个存在的数组，如何添加一个用0填充的边界?

In [37]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)

print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# 以下表达式运行的结果分别是什么?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [38]:
print(0*np.nan)

nan


In [39]:
print(np.nan == np.nan)

False


In [40]:
print(np.inf > np.nan)

False


In [41]:
print(np.nan-np.nan)

nan


In [42]:
print(0.3 == 3*0.1)

False


# 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [53]:
Z = np.diag(1+np.arange(4),k = -1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [44]:
np.info(np.diag)

 diag(v, k=0)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> x = np.ar

# 创建一个8x8 的矩阵，并且设置成棋盘样式

In [61]:
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [66]:
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


In [67]:
np.info(np.unravel_index)

unravel_index(indices, dims, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``dims``. Before version 1.6.0,
    this function accepted just one index value.
dims : tuple of ints
    The shape of the array to use for unraveling ``indices``.
order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unravel_index([31, 41, 13], (7,6), order='F')
(array([3, 6, 6]), array([4, 5, 1]))

>>> np.unravel_index

# 用tile函数创建一个8*8的棋盘样式矩阵

In [4]:
Z = np.tile(np.array([[0,1],[0,1]]),(4,4))

In [5]:
print(Z)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [8]:
Z = np.random.random((5,5))

In [11]:
Zmax , Zmin = Z.max(), Z.min()

In [12]:
Z = (Z-Zmin)/(Zmax-Zmin)

In [13]:
print(Z)

[[0.634493   0.6079486  0.69148495 0.38180672 0.26429534]
 [0.10908827 0.         0.49264757 0.53992937 0.22813921]
 [0.43357864 0.84380997 0.47870863 0.07298535 0.70549104]
 [0.74635652 0.17306901 0.33661295 0.32801042 1.        ]
 [0.99323753 0.50848901 0.14986334 0.93848131 0.6618785 ]]


# 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype

In [15]:
color = np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])

In [16]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

# 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [17]:
Z = np.dot(np.ones((5,3)),np.ones((3,2)))

In [19]:
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# 给定一个一维数组，对其在3到8之间的所有元素取反

In [20]:
Z = np.arange(11)

In [24]:
Z[(3 < Z) & (Z <= 8)] *= -1

In [25]:
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

# 下面脚本运行后的结果是什么

In [26]:
print(sum(range(5),-1))

9


In [29]:
from numpy import *
print(sum(range(5),-1))

10


# 考虑一个整数向量Z,下列表达合法的是哪个?

In [30]:
Z = np.arange(5)

In [33]:
Z

array([0, 1, 2, 3, 4])

In [31]:
Z**Z

array([  1,   1,   4,  27, 256], dtype=int32)

In [32]:
2<<Z>>2

array([0, 1, 2, 4, 8], dtype=int32)

In [34]:
Z<-Z

array([False, False, False, False, False])

In [36]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [37]:
Z/1/1

array([0., 1., 2., 3., 4.])

In [38]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
np.array(0) / np.array(0)

D:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [40]:
np.array(0) // np.array(0)

D:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [41]:
np.array(0) // np.array(0)

D:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

# 如何从零位对浮点数组做舍入

In [43]:
Z = np.random.uniform(-10,+10,10)

In [44]:
Z

array([ 2.11873709, -2.84025905, -4.89316464,  1.30108419,  2.53302508,
       -7.85130299,  2.83127613, -1.94769624,  4.27321646,  7.87254107])

In [48]:
np.copysign(np.ceil(np.abs(Z)), Z)

array([ 3., -3., -5.,  2.,  3., -8.,  3., -2.,  5.,  8.])

# 如何找到两个数组中的共同元素

In [49]:
Z1 = np.random.randint(0,10,10)

In [50]:
Z2 = np.random.randint(0,10,10)

In [52]:
np.intersect1d(Z1,Z2)

array([0, 4, 7])

# 如何忽略所有的 numpy 警告(尽管不建议这么做)

In [53]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# 下面的表达式是正确的吗?

In [54]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

# 如何得到昨天，今天，明天的日期

In [57]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

In [58]:
today     = np.datetime64('today', 'D')

In [59]:
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

# 如何得到所有与2016年7月对应的日期

In [60]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

In [61]:
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

# 如何直接在位计算(A+B)\*(-A/2)(不建立副本)

In [62]:
A = np.ones(3)*1

In [63]:
B = np.ones(3)*2

In [ ]:
C = np.ones(3)*3

In [64]:
np.add(A,B,out=B)

array([3., 3., 3.])

In [65]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [66]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [67]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

# 用五种不同的方法去提取一个随机数组的整数部分

In [68]:
Z = np.random.uniform(0,10,10)

In [71]:
Z-Z%1

array([3., 5., 0., 8., 9., 8., 9., 7., 1., 6.])

In [72]:
np.floor(Z)

array([3., 5., 0., 8., 9., 8., 9., 7., 1., 6.])

In [73]:
np.ceil(Z)-1

array([3., 5., 0., 8., 9., 8., 9., 7., 1., 6.])

In [74]:
Z.astype(int)

array([3, 5, 0, 8, 9, 8, 9, 7, 1, 6])

In [75]:
np.trunc(Z)

array([3., 5., 0., 8., 9., 8., 9., 7., 1., 6.])

# 创建一个5x5的矩阵，其中每行的数值范围从0到4 

In [76]:
Z = np.zeros((5,5))

In [77]:
Z = Z + np.arange(5)

In [78]:
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

# 通过考虑一个可生成10个整数的函数，来构建一个数组

In [79]:
def generate():
    for x in range(10):
        yield x

In [80]:
Z = np.fromiter(generate(),dtype = float,count = -1)

In [81]:
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [83]:
Z = np.linspace(0,1,11,endpoint = False)[1:]

In [85]:
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

# 创建一个长度为10的随机向量，并将其排序

In [86]:
Z = np.random.random(10)

In [88]:
Z.sort()

In [89]:
Z

array([0.0032797 , 0.00813809, 0.05688313, 0.13388591, 0.18638738,
       0.42729475, 0.4419457 , 0.47798626, 0.54023098, 0.78934008])

# 对于一个小数组，如何用比 np.sum更快的方式对其求和

In [90]:
Z = np.arange(10)

In [91]:
np.add.reduce(Z)

45

# 对于两个随机数组A和B，检查它们是否相等

In [92]:
A = np.random.randint(0,2,5)

In [93]:
B = np.random.randint(0,2,5)

In [94]:
equal = np.allclose(A,B)

In [95]:
equal

False

# 创建一个只读数组(read-only) 

In [96]:
Z = np.zeros(10)

In [98]:
Z.flags.writeable = False

In [99]:
Z[0]

0.0

# 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [100]:
Z = np.random.random((10,2))

In [101]:
X,Y = Z[:,0], Z[:,1]

In [102]:
R = np.sqrt(X**2+Y**2)

In [103]:
T = np.arctan2(Y,X)

In [104]:
R

array([0.61739842, 1.09061081, 1.05931476, 0.9289943 , 0.71321295,
       1.08913753, 0.67484278, 0.8745991 , 0.75288941, 0.93483072])

In [105]:
T

array([1.44267863, 0.77166202, 1.11025943, 0.5626975 , 0.00399386,
       0.65021566, 1.42934662, 0.04891834, 0.1671894 , 0.61243842])

# 创建一个长度为10的向量，并将向量中最大值替换为1

In [106]:
Z = np.random.random(10)

In [109]:
Z[Z.argmax()] = 1

In [110]:
Z

array([1.        , 0.21149216, 0.03465223, 0.        , 0.38655836,
       0.60027954, 0.89772074, 0.1018375 , 0.84290423, 0.39099082])

# 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 

In [111]:
Z = np.zeros((5,5), [('x',float),('y',float)])

In [113]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                           np.linspace(0,1,5))

In [114]:
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

# 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [115]:
X = np.arange(8)

In [116]:
Y = X + 0.5

In [117]:
C = 1.0 / np.subtract.outer(X, Y)

In [118]:
np.linalg.det(C)

3638.1636371179666

# 打印每个numpy标量类型的最小值和最大值

In [121]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [122]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


# 如何打印一个数组中的所有数值?

In [123]:
np.set_printoptions(threshold=np.nan)

In [124]:
Z = np.zeros((16,16))

In [125]:
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

# 给定标量时，如何找到数组中最接近标量的值？

In [126]:
Z = np.arange(100)

In [127]:
v = np.random.uniform(0,100)

In [128]:
index = (np.abs(Z-v)).argmin()

In [129]:
print (Z[index])

36
